/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;
import calculadora.Calculador;
import java.awt.Color;
import java.awt.Font;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Juan Soto
 */
public class History_Manager extends javax.swing.JFrame {
DefaultTableModel modelo;
int con = calculadora.Calculador.con;
        Object[] valores = new Object[10];
        
Color customBackground = new Color(144, 224, 239);        
Color customHeader = new Color(0, 119, 182);
    /**
     * Creates new form History_Manager
     */
    public History_Manager() {
        
        setLocationRelativeTo(null);
        initComponents();
        TablaHist();
        
        
    }
void TablaHist() {
    JTableHeader header = tabla.getTableHeader();
        Font headerFont = new Font("Dialog", Font.BOLD, 12); 
        header.setFont(headerFont);
        header.setBackground(customHeader);
        header.setForeground(Color.white);
    tabla.setBackground(customBackground);
    
    llenado();
    int con = calculadora.Calculador.con;
        if(con>10){
            con = 10;
        }
        
        String[] columnas = {"Historial"};
        modelo = new DefaultTableModel(columnas, con);
        for (int i = 0; i < con && i < 10; i++) {
            Object[] m = new Object[10];
            m[0] = valores[i];
            modelo.insertRow(0, m);
        } 
        
        tabla.setModel(modelo);
        tabla = new JTable(modelo);
        this.setTitle("Historial");
        this.setSize(400, 250);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

void llenado(){
        for(int i = 0; i < con && i < 10 ;i++){
            valores[i] = String.valueOf(calculadora.Calculador.hist[i]);
            //JOptionPane.showMessageDialog(null, valores[i]);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(202, 240, 248));

        tabla.setBackground(new java.awt.Color(144, 224, 239));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        if(evt.getButton()==1){
            int fila = tabla.getSelectedRow();
            fila = fila + 1;
            calculadora.Calculador.A = "0";
            calculadora.Calculador.operator = null;
            calculadora.Calculador.B = null;
            Object a = tabla.getValueAt(0, fila);
            calculadora.Calculador.displayLabel.setText(""+a);
            this.setVisible(false);
        }
    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History_Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
